(** D1 gate B — live wire check (PLAN.md D1, §12.6).

    Proves the vendored Zerobus proto, generated by [ocaml-protoc] (gate A) and
    used by the SDK, matches the LIVE service: it encodes a real [EphemeralStream]
    exchange with the generated wire types and sends it over the already-proven
    native transport (TLS 1.3 + ALPN h2 + scoped OAuth) to the real Zerobus gRPC
    endpoint, then asserts the server ACCEPTS THE FRAMING — i.e. replies with a
    well-formed [CreateIngestStreamResponse] (a stream_id) and durability acks,
    not a decode/parse error or a transport rejection.

    Uses JSON record ingestion ([RecordType.JSON]) so no protobuf DescriptorProto
    is needed — the point of gate B is the wire framing against the live service,
    which JSON exercises fully (CreateIngestStream + IngestRecord over the bidi
    [EphemeralStream] RPC, offsets, durability acks).

    Credentials + target come from env (never logged):
      DATABRICKS_HOST, ZEROBUS_WORKSPACE_ID, ZEROBUS_CLIENT_ID,
      ZEROBUS_CLIENT_SECRET, ZEROBUS_TABLE, ZEROBUS_ENDPOINT (grpc host:port).

    Exit 0 = gate B PASS. *)

module Z = Zerobus_proto.Zerobus_service

let ( let* ) = Lwt.bind
let env k = try Sys.getenv k with Not_found -> failwith ("missing env: " ^ k)

(* ---- §12.2 scoped-OAuth token mint (reused from oauth_token.ml) ---- *)

let authorization_details ~table =
  match String.split_on_char '.' table with
  | [ cat; sch; _ ] ->
      Printf.sprintf
        {|[{"type":"unity_catalog_privileges","privileges":["USE CATALOG"],"object_type":"CATALOG","object_full_path":"%s"},{"type":"unity_catalog_privileges","privileges":["USE SCHEMA"],"object_type":"SCHEMA","object_full_path":"%s.%s"},{"type":"unity_catalog_privileges","privileges":["MODIFY","SELECT"],"object_type":"TABLE","object_full_path":"%s"}]|}
        cat cat sch table
  | _ -> failwith ("ZEROBUS_TABLE must be catalog.schema.table, got: " ^ table)

let mint_token () : string Lwt.t =
  let host = env "DATABRICKS_HOST" in
  let wsid = env "ZEROBUS_WORKSPACE_ID" in
  let client_id = env "ZEROBUS_CLIENT_ID" in
  let client_secret = env "ZEROBUS_CLIENT_SECRET" in
  let table = env "ZEROBUS_TABLE" in
  let resource =
    Printf.sprintf "api://databricks/workspaces/%s/zerobusDirectWriteApi" wsid
  in
  let body_str =
    String.concat "&"
      [ "grant_type=client_credentials"; "scope=all-apis";
        "resource=" ^ Uri.pct_encode ~component:`Query_value resource;
        "authorization_details="
        ^ Uri.pct_encode ~component:`Query_value (authorization_details ~table) ]
  in
  let basic = Base64.encode_string (client_id ^ ":" ^ client_secret) in
  let headers =
    Cohttp.Header.of_list
      [ ("Content-Type", "application/x-www-form-urlencoded");
        ("Authorization", "Basic " ^ basic) ]
  in
  let* resp, body =
    Cohttp_lwt_unix.Client.post ~headers
      ~body:(Cohttp_lwt.Body.of_string body_str)
      (Uri.of_string (host ^ "/oidc/v1/token"))
  in
  let code = Cohttp.Response.status resp |> Cohttp.Code.code_of_status in
  let* body_str = Cohttp_lwt.Body.to_string body in
  if code < 200 || code >= 300 then
    Lwt.fail_with (Printf.sprintf "token HTTP %d" code)
  else
    match Yojson.Safe.from_string body_str with
    | `Assoc l -> (
        match List.assoc_opt "access_token" l with
        | Some (`String t) -> Lwt.return t
        | _ -> Lwt.fail_with "no access_token")
    | _ -> Lwt.fail_with "bad token json"

(* ---- proto framing with the generated (gate-A) types ---- *)

let enc_req (r : Z.ephemeral_stream_request) : string =
  let e = Pbrt.Encoder.create () in
  Z.encode_pb_ephemeral_stream_request r e;
  Pbrt.Encoder.to_string e

let dec_resp (s : string) : Z.ephemeral_stream_response =
  Z.decode_pb_ephemeral_stream_response (Pbrt.Decoder.of_string s)

(* gRPC length-prefix framing over raw h2 (proven in spike/): 1 compressed-flag
   byte (0) + 4-byte big-endian length + protobuf bytes. We drive h2 directly and
   FLUSH, because grpc-lwt 0.2.0's client sender omits the flush (§6.5) — harmless
   in-process but it stalls a real remote server that waits for the request. *)
let frame (msg : string) : string =
  let len = String.length msg in
  let b = Buffer.create (5 + len) in
  Buffer.add_char b '\000';
  Buffer.add_char b (Char.chr ((len lsr 24) land 0xff));
  Buffer.add_char b (Char.chr ((len lsr 16) land 0xff));
  Buffer.add_char b (Char.chr ((len lsr 8) land 0xff));
  Buffer.add_char b (Char.chr (len land 0xff));
  Buffer.add_string b msg;
  Buffer.contents b

let deframe (acc : string) : string list * string =
  let rec loop acc msgs =
    if String.length acc < 5 then (List.rev msgs, acc)
    else
      let len =
        (Char.code acc.[1] lsl 24) lor (Char.code acc.[2] lsl 16)
        lor (Char.code acc.[3] lsl 8) lor Char.code acc.[4]
      in
      if String.length acc < 5 + len then (List.rev msgs, acc)
      else
        loop (String.sub acc (5 + len) (String.length acc - 5 - len))
          (String.sub acc 5 len :: msgs)
  in
  loop acc []

(* ---- TLS+ALPN h2 connect (ported from tls_alpn.ml / zerobus_io_lwt) ---- *)

let connect_tls host port =
  let* addrs =
    Lwt_unix.getaddrinfo host (string_of_int port)
      [ Unix.(AI_SOCKTYPE SOCK_STREAM) ]
  in
  let* sockaddr =
    match addrs with
    | ai :: _ -> Lwt.return ai.Unix.ai_addr
    | [] -> Lwt.fail_with ("no address for " ^ host)
  in
  let fd = Lwt_unix.socket Unix.PF_INET Unix.SOCK_STREAM 0 in
  let* () = Lwt_unix.connect fd sockaddr in
  let authenticator =
    match Ca_certs.authenticator () with
    | Ok a -> a
    | Error (`Msg m) -> failwith ("ca-certs: " ^ m)
  in
  let peer_name =
    match Domain_name.of_string host with
    | Ok d -> ( match Domain_name.host d with Ok h -> Some h | Error _ -> None)
    | Error _ -> None
  in
  let cfg =
    Tls.Config.client ~authenticator ?peer_name ~alpn_protocols:[ "h2" ] ()
  in
  let* tls = Tls_lwt.Unix.client_of_fd cfg fd in
  (match Tls_lwt.Unix.epoch tls with
   | Ok e when e.Tls.Core.alpn_protocol = Some "h2" -> ()
   | Ok _ -> failwith "ALPN != h2"
   | Error () -> failwith "no TLS epoch");
  H2_lwt_unix.Client.TLS.create_connection ~error_handler:(fun _ -> ()) tls

let () =
  Lwt_main.run
    (let table = env "ZEROBUS_TABLE" in
     let endpoint = env "ZEROBUS_ENDPOINT" in
     let host, port =
       match String.split_on_char ':' endpoint with
       | [ h; p ] -> (h, int_of_string p)
       | _ -> (endpoint, 443)
     in
     Printf.printf "== D1 gate B — live wire check ==\nendpoint: %s:%d\ntable: %s\n%!"
       host port table;

     let* token = mint_token () in
     Printf.printf "oauth: scoped token minted (value not logged)\n%!";

     let* conn = connect_tls host port in
     Printf.printf "tls: connected, ALPN h2\n%!";

     (* Build the EphemeralStream exchange: create-stream (JSON) then one record. *)
     let create =
       Z.Create_stream
         (Z.make_create_ingest_stream_request ~table_name:table
            ~record_type:Z.Json ())
     in
     let record =
       Z.Ingest_record
         (Z.make_ingest_record_request ~offset_id:0L
            ~record:(Z.Json_record {|{"id": 1, "name": "gate-b"}|}) ())
     in

     let got_create_resp = ref false in
     let got_ack = ref false in
     let stream_id = ref "" in
     let proto_error = ref None in

     let grpc_status = ref "(none)" in
     let http_status = ref "(none)" in

     (* Raw h2 gRPC request, driven directly so we can FLUSH after each frame. *)
     let req =
       H2.Request.create ~scheme:"https" `POST
         "/databricks.zerobus.Zerobus/EphemeralStream"
         ~headers:
           (H2.Headers.of_list
              [ (* :authority is required by gRPC servers (h2 pseudo-header). *)
                (":authority", host);
                ("te", "trailers");
                ("content-type", "application/grpc+proto");
                ("grpc-encoding", "identity");
                ("user-agent", "zerobus-ocaml-sdk/0.0.0-gateb");
                ("authorization", "Bearer " ^ token);
                ("x-databricks-zerobus-table-name", table) ])
     in
     let done_p, done_u = Lwt.wait () in
     let resp_acc = ref "" in
     let response_handler (response : H2.Response.t) body =
       http_status := H2.Status.to_string response.H2.Response.status;
       (* capture grpc-status trailer if present *)
       (match H2.Headers.get response.H2.Response.headers "grpc-status" with
        | Some s -> grpc_status := "grpc-status=" ^ s
        | None -> ());
       let rec on_read bs ~off ~len =
         resp_acc := !resp_acc ^ Bigstringaf.substring bs ~off ~len;
         let msgs, rest = deframe !resp_acc in
         resp_acc := rest;
         List.iter
           (fun raw ->
             match dec_resp raw with
             | Z.Create_stream_response r ->
                 got_create_resp := true;
                 stream_id := r.Z.stream_id
             | Z.Ingest_record_response _ -> got_ack := true
             | Z.Close_stream_signal _ -> ()
             | exception Pbrt.Decoder.Failure _ -> proto_error := Some "decode failure")
           msgs;
         H2.Body.Reader.schedule_read body ~on_read ~on_eof
       and on_eof () = if Lwt.is_sleeping done_p then Lwt.wakeup_later done_u () in
       H2.Body.Reader.schedule_read body ~on_read ~on_eof
     in
     let trailers_handler (h : H2.Headers.t) =
       match H2.Headers.get h "grpc-status" with
       | Some s ->
           grpc_status :=
             "grpc-status=" ^ s
             ^ (match H2.Headers.get h "grpc-message" with
                | Some m -> " (" ^ m ^ ")" | None -> "")
       | None -> ()
     in
     let h2_err = ref "(none)" in
     let body_writer =
       H2_lwt_unix.Client.TLS.request conn req
         ~error_handler:(fun e ->
           h2_err :=
             (match e with
              | `Malformed_response s -> "malformed_response: " ^ s
              | `Invalid_response_body_length _ -> "invalid_response_body_length"
              | `Protocol_error (_, s) -> "protocol_error: " ^ s
              | `Exn ex -> "exn: " ^ Printexc.to_string ex);
           if Lwt.is_sleeping done_p then Lwt.wakeup_later done_u ())
         ~trailers_handler ~response_handler
     in
     (* Write the two framed messages, FLUSHING each (the fix for §6.5). *)
     let write_frame msg =
       H2.Body.Writer.write_string body_writer (frame msg);
       let flushed, u = Lwt.wait () in
       H2.Body.Writer.flush body_writer (fun () ->
           if Lwt.is_sleeping flushed then Lwt.wakeup_later u ());
       flushed
     in
     let* () = write_frame (enc_req create) in
     let* () = write_frame (enc_req record) in
     H2.Body.Writer.close body_writer;
     (* Bound the exchange so a stalled stream reports instead of hanging. *)
     let timed_out = ref false in
     let timeout =
       let* () = Lwt_unix.sleep 20.0 in
       timed_out := true;
       Lwt.return_unit
     in
     let* () = Lwt.pick [ done_p; timeout ] in
     let* () =
       Lwt.catch
         (fun () -> H2_lwt_unix.Client.TLS.shutdown conn)
         (fun _ -> Lwt.return_unit)
     in
     let t = Unix.gmtime (Unix.time ()) in
     let status_str =
       Printf.sprintf "http=%s %s | h2_err=%s" !http_status !grpc_status !h2_err
     in
     Printf.printf
       "\n-- EVIDENCE (D1 gate B) --\n\
        timestamp_utc  : %04d-%02d-%02dT%02d:%02d:%02dZ\n\
        rpc            : databricks.zerobus.Zerobus/EphemeralStream (bidi, TLS h2)\n\
        proto          : vendored zerobus_service.proto via ocaml-protoc (gate A)\n\
        create_stream_response: %b (stream_id=%s)\n\
        durability_ack : %b\n\
        grpc_status    : %s\n\
        timed_out      : %b\n\
        decode_error   : %s\n%!"
       (t.tm_year + 1900) (t.tm_mon + 1) t.tm_mday t.tm_hour t.tm_min t.tm_sec
       !got_create_resp !stream_id !got_ack status_str !timed_out
       (match !proto_error with Some e -> e | None -> "none");

     (* Gate B passes if the server accepted our framing: we got a well-formed
        CreateIngestStreamResponse back and no proto decode error. A durability
        ack is a bonus (confirms the record was framed acceptably too). *)
     if !got_create_resp && !proto_error = None then begin
       Printf.printf
         "RESULT: PASS — live service accepted the generated-proto framing.\n%!";
       Lwt.return_unit
     end
     else begin
       Printf.printf "RESULT: FAIL — server did not accept the framing cleanly.\n%!";
       exit 1
     end)
